# Generated by Django 2.1.5 on 2019-01-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidopt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Record_ID', models.IntegerField()),
                ('Record_Type', models.CharField(max_length=200)),
                ('Campaign_ID', models.IntegerField()),
                ('Campaign', models.CharField(max_length=200)),
                ('Budget', models.DecimalField(decimal_places=15, max_digits=30)),
                ('Portofolio_ID', models.IntegerField()),
                ('Campaign_Start_Date', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Record_ID', models.IntegerField()),
                ('Record_Type', models.CharField(max_length=200)),
                ('Campaign_ID', models.IntegerField()),
                ('Campaign', models.CharField(max_length=200)),
                ('Budget', models.DecimalField(decimal_places=15, max_digits=30)),
                ('Portofolio_ID', models.IntegerField()),
                ('Campaign_Start_Date', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Record_ID', models.IntegerField()),
                ('Record_Type', models.CharField(max_length=200)),
                ('Campaign_ID', models.IntegerField()),
                ('Campaign', models.CharField(max_length=200)),
                ('Budget', models.DecimalField(decimal_places=15, max_digits=30)),
                ('Portofolio_ID', models.IntegerField()),
                ('Campaign_Start_Date', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
